services:
    db:
        image: postgres:17
        container_name: db
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-api_db}
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    pgbouncer:
        image: rmccaffrey/pgbouncer:latest
        container_name: pgbouncer
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: ${POSTGRES_USER:-postgres}
            DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POOL_MODE: transaction
            MAX_CLIENT_CONN: 100
            DEFAULT_POOL_SIZE: 20
            AUTH_TYPE: scram-sha-256
        ports:
            - "6432:5432"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s


networks:
    backend:

volumes:
    pg_data: